import 'dart:async';
import 'dart:convert';

import 'package:elluminati_project/models/generated.dart';
import 'package:flutter/material.dart';

import 'package:flutter/services.dart';
import 'package:stacked/stacked.dart';

class HomeViewModel extends BaseViewModel {
  Autogenerated? autogenerated;

  int? value = 1;
  int totalValue = 1;
  int price = 999;

  bool shouldShowAppBar = false;

  ScrollController apartmentControl = ScrollController();

  HomeViewModel({this.autogenerated}) {
    apartmentControl.addListener(handleScrollControl);
  }

  void handleScrollControl() {
    if (apartmentControl.position.extentAfter > 500) {
      shouldShowAppBar = true;
      notifyListeners();
    } else {
      shouldShowAppBar = false;
      notifyListeners();
    }
  }

  Future<void> readJson() async {
    final String response = await rootBundle.loadString('assets/response.json');

    final data = await json.decode(response);
    autogenerated = Autogenerated.fromMap(data);

    notifyListeners();
  }
}
