import 'dart:async';
import 'dart:convert';

import 'package:elluminati_project/models/generated.dart';
import 'package:flutter/material.dart';

import 'package:flutter/services.dart';
import 'package:stacked/stacked.dart';

class HomeViewModel extends BaseViewModel {
  Autogenerated? autogenerated;

  int? value = 1;
  int totalValue = 1;
  int price = 999;

  String? findId;

  bool shouldShowAppBar = false;

  ScrollController apartmentControl = ScrollController();

  List<Specification>? specification = [];

  HomeViewModel({this.autogenerated}) {
    apartmentControl.addListener(handleScrollControl);
  }

  void handleScrollControl() {
    if (apartmentControl.position.extentBefore > 200) {
      shouldShowAppBar = true;
      notifyListeners();
    } else {
      shouldShowAppBar = false;
      notifyListeners();
    }
  }

  Future<void> readJson() async {
    final String response = await rootBundle.loadString('assets/response.json');

    final data = await json.decode(response);
    autogenerated = Autogenerated.fromMap(data);

    if (autogenerated != null) {
      specification = autogenerated!.specifications.where((element) {
        return element.modifierId == '621da764abb8a52242c181e5';
      }).toList();
    }
    notifyListeners();
  }

  void handleFindId(String id) {
    findId = id;
    notifyListeners();

    specification = autogenerated!.specifications.where((element) {
      return element.modifierId == findId;
    }).toList();
    notifyListeners();
  }
}
