class Autogenerated {
  String id;
  List<String> name;
  int price;
  List<int> itemTaxes;
  List<Specifications> specifications;

  Autogenerated({
    required this.id,
    required this.name,
    required this.price,
    required this.itemTaxes,
    required this.specifications,
  });

  factory Autogenerated.fromMap(Map<String, dynamic> map) {
    return Autogenerated(
      id: map['_id'].toString(),
      name: List<String>.from(map['name']),
      price: map['price'],
      itemTaxes: List<int>.from(map['itemTaxes']),
      specifications: (map['specifications'] as List)
          .map((e) => Specifications.fromMap(e))
          .toList(),
    );
  }
}

class Specifications {
  String sId;
  List<String> name;
  int sequenceNumber;
  int uniqueId;
  List<List1> list;
  int maxRange;
  int range;
  int type;
  bool isRequired;
  bool isParentAssociate;
  String modifierId;
  String modifierGroupId;
  String modifierGroupName;
  String modifierName;
  bool isAssociated;
  bool userCanAddSpecificationQuantity;

  Specifications({
    required this.sId,
    required this.name,
    required this.sequenceNumber,
    required this.uniqueId,
    required this.list,
    required this.maxRange,
    required this.range,
    required this.type,
    required this.isRequired,
    required this.isParentAssociate,
    required this.modifierId,
    required this.modifierGroupId,
    required this.modifierGroupName,
    required this.modifierName,
    required this.isAssociated,
    required this.userCanAddSpecificationQuantity,
  });

  factory Specifications.fromMap(Map<String, dynamic> map) {
    return Specifications(
      sId: map['_id'],
      name: List<String>.from(map['name']),
      sequenceNumber: map['sequenceNumber'],
      uniqueId: map['uniqueId'],
      list: (map['list'] as List).map((e) => List1.fromMap(e)).toList(),
      maxRange: map['maxRange'],
      range: map['range'],
      type: map['type'],
      isRequired: map['isRequired'],
      isParentAssociate: map['isParentAssociate'],
      modifierId: map['modifierId'],
      modifierGroupId: map['modifierGroupId'],
      modifierGroupName: map['modifierGroupName'],
      modifierName: map['modifierName'],
      isAssociated: map['isAssociated'],
      userCanAddSpecificationQuantity: map['userCanAddSpecificationQuantity'],
    );
  }
}

class List1 {
  String sId;
  List<String> name;
  int price;
  int sequenceNumber;
  bool isDefaultSelected;
  String specificationGroupId;
  int uniqueId;

  List1({
    required this.sId,
    required this.name,
    required this.price,
    required this.sequenceNumber,
    required this.isDefaultSelected,
    required this.specificationGroupId,
    required this.uniqueId,
  });

  factory List1.fromMap(Map<String, dynamic> map) {
    return List1(
      sId: map['_id'],
      name: List<String>.from(map['name']),
      price: map['price'],
      sequenceNumber: map['sequenceNumber'],
      isDefaultSelected: map['sequenceNumber'],
      specificationGroupId: map['specificationGroupId'],
      uniqueId: map['uniqueId'],
    );
  }
}
