part of 'generated.dart';

class Autogenerated {
  String id;
  List<String> name;
  int price;
  List<int> itemTaxes;
  List<Specification> specifications;

  Autogenerated({
    required this.id,
    required this.name,
    required this.price,
    required this.itemTaxes,
    required this.specifications,
  });

  factory Autogenerated.fromMap(Map<String, dynamic> map) {
    return Autogenerated(
      id: map['_id'].toString(),
      name: List<String>.from(map['name']),
      price: map['price'],
      itemTaxes: List<int>.from(map['item_taxes']),
      specifications: (map['specifications'] as List)
          .map((e) => Specification.fromMap(e))
          .toList(),
    );
  }
}

class Specification {
  String sId;
  List<String> name;
  int sequenceNumber;
  int uniqueId;
  List<List1> list;
  int maxRange;
  int range;
  int type;
  bool isRequired;
  bool? isParentAssociate;
  String modifierId;
  String modifierGroupId;
  String modifierGroupName;
  String modifierName;
  bool? isAssociated;
  bool? userCanAddSpecificationQuantity;

  Specification({
    required this.sId,
    required this.name,
    required this.sequenceNumber,
    required this.uniqueId,
    required this.list,
    required this.maxRange,
    required this.range,
    required this.type,
    required this.isRequired,
    required this.isParentAssociate,
    required this.modifierId,
    required this.modifierGroupId,
    required this.modifierGroupName,
    required this.modifierName,
    required this.isAssociated,
    required this.userCanAddSpecificationQuantity,
  });

  factory Specification.fromMap(Map<String, dynamic> map) {
    return Specification(
      sId: map['_id'],
      name: List<String>.from(map['name']),
      sequenceNumber: map['sequence_number'],
      uniqueId: map['unique_id'],
      list: (map['list'] as List).map((e) => List1.fromMap(e)).toList(),
      maxRange: map['max_range'],
      range: map['range'],
      type: map['type'],
      isRequired: map['is_required'],
      isParentAssociate: map['isParentAssociate'],
      modifierId: map['modifierId'].toString(),
      modifierGroupId: map['modifierGroupId'].toString(),
      modifierGroupName: map['modifierGroupName'].toString(),
      modifierName: map['modifierName'].toString(),
      isAssociated: map['isAssociated'],
      userCanAddSpecificationQuantity:
          map['user_can_add_specification_quantity'],
    );
  }
}

class List1 {
  String sId;
  List<String> name;
  int price;
  int sequenceNumber;
  bool isDefaultSelected;
  String specificationGroupId;
  int uniqueId;

  List1({
    required this.sId,
    required this.name,
    required this.price,
    required this.sequenceNumber,
    required this.isDefaultSelected,
    required this.specificationGroupId,
    required this.uniqueId,
  });

  factory List1.fromMap(Map<String, dynamic> map) {
    return List1(
        sId: map['_id'],
        name: List<String>.from(map['name']),
        price: map['price'],
        sequenceNumber: map['sequence_number'],
        isDefaultSelected: map['is_default_selected'],
        specificationGroupId: map['specification_group_id'],
        uniqueId: map['unique_id']);
  }
}
